/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CardComponent {
        "cardClass": string;
        "cardHeaderClass": string;
        "cardTitle": string | null;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyFirstComponent {
        "blockIntro": string;
        "blockTitle": string;
    }
    interface MyInput {
        "inputAppearance": string;
        "inputId": string;
        "inputLabel": string;
        "inputPlaceholder": string;
        "inputType": string;
    }
}
export interface MyInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyInputElement;
}
declare global {
    interface HTMLCardComponentElement extends Components.CardComponent, HTMLStencilElement {
    }
    var HTMLCardComponentElement: {
        prototype: HTMLCardComponentElement;
        new (): HTMLCardComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyFirstComponentElement extends Components.MyFirstComponent, HTMLStencilElement {
    }
    var HTMLMyFirstComponentElement: {
        prototype: HTMLMyFirstComponentElement;
        new (): HTMLMyFirstComponentElement;
    };
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    interface HTMLElementTagNameMap {
        "card-component": HTMLCardComponentElement;
        "my-component": HTMLMyComponentElement;
        "my-first-component": HTMLMyFirstComponentElement;
        "my-input": HTMLMyInputElement;
    }
}
declare namespace LocalJSX {
    interface CardComponent {
        "cardClass"?: string;
        "cardHeaderClass"?: string;
        "cardTitle"?: string | null;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyFirstComponent {
        "blockIntro"?: string;
        "blockTitle"?: string;
    }
    interface MyInput {
        "inputAppearance"?: string;
        "inputId"?: string;
        "inputLabel"?: string;
        "inputPlaceholder"?: string;
        "inputType"?: string;
        "onInputChange"?: (event: MyInputCustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "card-component": CardComponent;
        "my-component": MyComponent;
        "my-first-component": MyFirstComponent;
        "my-input": MyInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "card-component": LocalJSX.CardComponent & JSXBase.HTMLAttributes<HTMLCardComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-first-component": LocalJSX.MyFirstComponent & JSXBase.HTMLAttributes<HTMLMyFirstComponentElement>;
            "my-input": LocalJSX.MyInput & JSXBase.HTMLAttributes<HTMLMyInputElement>;
        }
    }
}
